### ISSUE TITLE
Installation without Gurobi

### ISSUE THREAD

**Issue by ghost** [cg3hci/Gen-Adapt-Ref-for-Hexmeshing#5]
Hi, is there a way to compile this library without Gurobi? Or can we use some other open-source library to replace Gurobi? 

I am using this library in the industry for CFD, but Gurobi is a bottleneck. 

Thank you for your responses.

**Comment by mlivesu** [comment]
Hi, we never attempted to switch from Gurobi to an open-source solver, albeit this is technically possible since all we need to solve is a sequence of standard linear problems. Based on my experience I expect a significant decay of the performances though, because Gurobi is far ahead than any open-source solver I am aware of...

Note that besides the ILP-based grid pairing our code also implements standard octree-based pairing, which is purely topological and does not rely on any external solver. If you want to use this feature then you should be able to just remove the dependency from Gurobi and comment out all the code that depends on it

**Comment by ghost** [comment]
Thank you for the response. I will try to use the octree-base pairing.
